sudo: required
services:
  - docker

before_install:
  - docker build -t tfushimi123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tfushimi123/docker-react npm run test -- --coverage
