sudo: required
services:
  - docker

before_install:
  - docker build -t tfushimi123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tfushimi123/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-386069677604"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    